import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [data, setData] = useState('')

  console.log(process.env)

  const baseUrl = () => {
    switch (process.env.NODE_ENV) {
      case 'development':
        return `http://localhost:${process.env.PORT ?? 3000} `
      case 'preview':
        return `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`
      default:
        return '' // if production, then empty string
    }
  }
  const getPage = async () => {
    const res = await fetch(`${baseUrl()}/api/getPage`)
    const data = await res.json()
    console.log('data', data)
  }



  const handleFetch = async () => {
    console.log(`starting fetch with url ${baseUrl()}/api/hello`)
    const res = await fetch(`${baseUrl()}/api/hello`, {
      method: 'GET',
      application: 'application/json',
    })
    console.log('res', res)
    const data = await res.json()
    console.log('data', data)
    setData(data.name)
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <p className={styles.description}>
          process.env.NODE_ENV:
          <code className={styles.code}>{process.env.NODE_ENV}</code>
        </p>
        <p className={styles.description}>
          process.env.VERCEL_URL:
          <code className={styles.code}>{process.env.VERCEL_URL}</code>
        </p>
        <p className={styles.description}>
          process.env.NEXT_PUBLIC_VERCEL_URL:
          <code className={styles.code}>{process.env.NEXT_PUBLIC_VERCEL_URL}</code>
        </p>

        <div>Fetch to url: {baseUrl()}/api/hello </div>
        <button onClick={handleFetch}>{`fetch`}</button>

        <div>Fetch response: {data}</div>


      </main>
    </div>
  )
}
